### ISSUE TITLE
Cannot handle meter plus device type

### ISSUE THREAD

**Issue by ietz** [kzosabe/switchbot-client#119]
Hello @kzosabe and thank you very much for open-sourcing this library. I would like to use it to read the current temperature and humidity of my Meter Plus devices but it always throws an error as soon as I call the `SwitchBotClient.devices` method. The error is a `TypeError` with the message `invalid physical device object`.

Looking through the source, I see that you instantiate the device objects based on the `deviceType` which is `MeterPlus` in my case. Your `DeviceType` does not have this value but a `Meter Plus (US)` and a `Meter Plus (JP)`. Just changing one of the Enum values to `MeterPlus` makes it work perfectly.

Looking at the [Meter Plus devices section in the SwitchBot API docs](https://github.com/OpenWonderLabs/SwitchBotAPI#meter-plus-1) it seems to me that the current values `Meter Plus (US)` and `Meter Plus (JP)` are simply incorrect and you only need the `MeterPlus` type like with `Meter`, no separate `MeterPlusUs` and `MeterPlusJp`

**Comment by kzosabe** [comment]
Thanks for the detailed error report! I'll check it out.
I only own some of the SwitchBot devices and cannot confirm that all of them work, so I am glad to get reports like this.
I will release a new version after the fix and would appreciate your comments if it works properly.

**Comment by ietz** [comment]
I just checked out the develop branch and can confirm that the Meter Plus devices do work now. Thanks a lot for the quick fix!
